
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Донгл – центральное устройство сплита
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=n

# Принимаем pointing-данные от периферии
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POINTING=y

# Количество подключаемых периферий (1 трекбол)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Эмуляция USB мыши
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_USB_POINTING=y
